from typing import Dict, Any
from app.services.ai.service import ai_service
from app.schemas.strategy import StrategyRequest, ChartAnalysisRequest

class StrategyService:
    async def generate(self, req: StrategyRequest) -> Dict[str, Any]:
        lang_map = {"pine_script": "Pine Script (TradingView)", "python": "Python", "mt5": "MT5 Expert Advisor (MQL5)"}
        target = lang_map.get(req.target_language, "Pine Script")
        prompt = f"Generate a {target} trading strategy based on this description:\n{req.description}\n"
        if req.additional_context:
            prompt += f"\nAdditional context: {req.additional_context}\n"
        prompt += "\nProvide the complete code with proper syntax. Also include documentation with entry rules, exit rules, stop loss, take profit, and risk management parameters."
        result = await ai_service.chat([{"role": "user", "content": prompt}], temperature=0.3, max_tokens=4000)
        return {"code": result["content"], "language": req.target_language, "documentation": "Generated by AI Trading Platform", "explanation": "Strategy generated from natural language description"}

    async def analyze_chart(self, req: ChartAnalysisRequest) -> Dict[str, Any]:
        prompt = f"Analyze this trading chart screenshot.\n\n"
        prompt += f"Symbol: {req.symbol or 'Unknown'}\n"
        prompt += f"Timeframe: {req.timeframe or 'Unknown'}\n\n"
        prompt += "Please identify:\n"
        prompt += "1. Chart patterns (head and shoulders, triangles, flags, wedges, channels, etc.)\n"
        prompt += "2. Key support and resistance levels\n"
        prompt += "3. Current trend direction and strength\n"
        prompt += "4. Overall setup quality score (1-100)\n"
        prompt += "5. Trading recommendations"
        messages = [{"role": "user", "content": [{"type": "text", "text": prompt}, {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{req.image_base64}"}}]}]
        result = await ai_service.chat(messages, temperature=0.3, max_tokens=2000)
        return {"patterns": ["detected_pattern"], "support_resistance": {"support": [], "resistance": []}, "trend": "analyzed", "setup_quality": "medium", "score": 50, "analysis": result["content"]}

strategy_service = StrategyService()
